### ISSUE TITLE
Tests for provisioning script are failing

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#1349]
```
____________________ test_basic_create_initial_data_for_dev_run _____________________
Traceback (most recent call last):
  File "/home/lemburg/egenix/projects/europython-2021/epcon/tests/test_provisioning_script.py", line 12, in test_basic_create_initial_data_for_dev_run
    call_command('create_initial_data_for_dev')
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "<pyrun>/contextlib.py", line 75, in inner
  File "/home/lemburg/egenix/projects/europython-2021/epcon/conference/management/commands/create_initial_data_for_dev.py", line 149, in handle
    program_page = new_page("faq", "FAQ")
  File "/home/lemburg/egenix/projects/europython-2021/epcon/conference/management/commands/create_initial_data_for_dev.py", line 140, in new_page
    publish_page(page, user=admin.user, language="en")
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/cms/api.py", line 431, in publish_page
    page.publish(language)
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/cms/models/pagemodel.py", line 989, in publish
    self._copy_contents(public_page, language)
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/cms/models/pagemodel.py", line 635, in _copy_contents
    placeholder.copy_plugins(target_placeholder, language=language)
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/cms/models/placeholdermodel.py", line 577, in copy_plugins
    new_plugins = copy_plugins_to_placeholder(
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/cms/utils/plugins.py", line 217, in copy_plugins_to_placeholder
    new_plugin = CMSPlugin.add_root(instance=new_plugin)
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/lemburg/egenix/projects/europython-2021/epcon/pycon-env/lib/python3.8/site-packages/treebeard/mp_tree.py", line 326, in process
    raise NodeAlreadySaved("Attempted to add a tree node that is "\
treebeard.exceptions.NodeAlreadySaved: Attempted to add a tree node that is already in the database
```

Skipped the test for now, but we'll need to get this fixed.

**Comment by kgaughan** [comment]
The fix for this is simple enough. Django-CMS's `cms.api.create_page` function is being passed `published=True`, so when `publish_page(page, user=admin.user, language="en")` is called further down the `new_page` function, it fails.

The simplest solution is to remove the call to `publish_page()` as it doesn't appear to be necessary, and to add `created_by=admin.user` to the arguments to `create_page()`. I can submit a PR with the fix later today.
