### ISSUE TITLE
`make init-env` generates traceback

### ISSUE THREAD

**Issue by supakeen** [EuroPython/epcon#1358]
Running `make init-env` generates the following traceback. `docker-compuse up` still works and gives a workable website.

```
WARNINGS:
assopy.Vat.fares: (fields.W340) null has no effect on ManyToManyField.
Creating an admin user
Creating regular users
Making some talk proposals
Making some accepted and waitlisted talks
Traceback (most recent call last):
  File "/code/./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/code/conference/management/commands/create_initial_data_for_dev.py", line 149, in handle
    program_page = new_page("registration", "Registration")
  File "/code/conference/management/commands/create_initial_data_for_dev.py", line 140, in new_page
    publish_page(page, user=admin.user, language="en")
  File "/usr/local/lib/python3.9/site-packages/cms/api.py", line 431, in publish_page
    page.publish(language)
  File "/usr/local/lib/python3.9/site-packages/cms/models/pagemodel.py", line 989, in publish
    self._copy_contents(public_page, language)
  File "/usr/local/lib/python3.9/site-packages/cms/models/pagemodel.py", line 635, in _copy_contents
    placeholder.copy_plugins(target_placeholder, language=language)
  File "/usr/local/lib/python3.9/site-packages/cms/models/placeholdermodel.py", line 577, in copy_plugins
    new_plugins = copy_plugins_to_placeholder(
  File "/usr/local/lib/python3.9/site-packages/cms/utils/plugins.py", line 217, in copy_plugins_to_placeholder
    new_plugin = CMSPlugin.add_root(instance=new_plugin)
  File "/usr/local/lib/python3.9/site-packages/treebeard/mp_tree.py", line 617, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/usr/local/lib/python3.9/site-packages/treebeard/mp_tree.py", line 326, in process
    raise NodeAlreadySaved("Attempted to add a tree node that is "\
treebeard.exceptions.NodeAlreadySaved: Attempted to add a tree node that is already in the database
make: *** [Makefile:66: init-db] Error 1
```

`docker-compose up` still works but the data in the database has not been created (useraccounts as documented do not work).

```
epcon_1  | Running migrations:
epcon_1  |   No migrations to apply.
epcon_1  |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
epcon_1  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.```

**Comment by supakeen** [comment]
Might be related to: https://github.com/EuroPython/epcon/issues/1349

**Comment by kgaughan** [comment]
This was fixed by #1358. Pull down the latest version of the dev/ep2021 branch from this repo, and you should be gold.

**Comment by fpierfed** [comment]
Any news on this? If it was fixed by #1358, we can close it.

**Comment by supakeen** [comment]
I'll check this tomorrow and update the ticket!

**Comment by fpierfed** [comment]
Looks like that fixed it :-) Feel free to re-open this is this issue comes back.
