### ISSUE TITLE
MultipleObjectsReturned for coupons

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#284]
```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/src/ep2016/p3/views/cart.py", line 92, in cart
    if form.is_valid():

  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 126, in is_valid
    return self.is_bound and not bool(self.errors)

  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 117, in _get_errors
    self.full_clean()

  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 272, in full_clean
    self._clean_fields()

  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 290, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()

  File "/usr/src/ep2016/p3/forms.py", line 705, in clean_coupon
    coupon = amodels.Coupon.objects.get(code__iexact=data)

  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get
    (self.model._meta.object_name, num))

MultipleObjectsReturned: get() returned more than one Coupon -- it returned 2!
```

**Comment by malemburg** [comment]
Checked the database: the coupon in question is only listed once, so either someone has already fixed this, or the system is getting two records via some other means.

**Comment by malemburg** [comment]
We just got a second traceback, so something else must be wrong.

**Comment by malemburg** [comment]
The problem is that the same code was used for EP2015, resulting in the code lookup not to be unique.
