### ISSUE TITLE
NameError in hcomments

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#493]
```
Internal Server Error: /hcomments/post
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/ep2017/hcomments/views.py", line 61, in post_comment
    comment.save()
  File "/usr/local/lib/python2.7/site-packages/mptt/models.py", line 992, in save
    super(MPTTModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_comments/abstracts.py", line 95, in save
    super(CommentAbstractModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/src/ep2017/hcomments/apps.py", line 20, in send_email_to_subscribers
    body = render_to_string('hcomments/thread_email.txt', ctx)
NameError: global name 'render_to_string' is not defined
```

**Comment by malemburg** [comment]
I believe @patrick91 already fixed this.
