### ISSUE TITLE
Conference stats page (partially) broken

### ISSUE THREAD

**Issue by alanderex** [EuroPython/epcon#542]
There are some important tools we are working with on the stats page:
https://ep2017.europython.eu/admin/conference/conference/ep2017/stats/

More are broken, the following are *important* for the schedule organisation, error checking and speaker updates.

### Speakers
   * Speakers with unscheduled accepted talks

 ### Speakers stats
   * Without ticket

**Comment by malemburg** [comment]
The relevant code is here:

https://github.com/EuroPython/epcon/blob/ep2017/p3/stats.py#L401

Could you be more specific about what you think is broken ?

**Comment by alanderex** [comment]
Please just click on the sections indicated it returns our favourite Basque witch poem

**Comment by malemburg** [comment]
I see what you mean :-)

The traceback indicates an incompatibility with Django 1.8:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/src/ep2017/conference/admin.py", line 198, in stats_details
    context_instance=template.RequestContext(request))
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 1554, in do_with
    nodelist = parser.parse(('endwith',))
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1096, in generic_tag_compiler
    defaults, takes_context, name)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1065, in parse_bits
    "keyword argument(s)" % name)
TemplateSyntaxError: 'paginate' received some positional argument(s) after some keyword argument(s)
```

**Comment by alanderex** [comment]
How serious is this? (sorry I don't speak Django) Can we get it fixed soon? 
It's the only way for the program WG to check if speakers have a ticket assigned
and crosscheck schedule assignments.
