### ISSUE TITLE
Encoding error in ical module

### ISSUE THREAD

**Issue by malemburg** [EuroPython/epcon#555]
From the log:
```
2017-06-07 19:00:43,368 [13] ERROR - django.request - base - handle_uncaught_exception: Internal Server Error: /p3/schedule/ep2017.ics
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/ep2017/p3/views/schedule.py", line 144, in schedule_ics
    return http.HttpResponse(list(cal.encode()), content_type='text/calendar')
  File "/usr/src/ep2017/conference/ical.py", line 103, in encode
    for line in comp.encode():
  File "/usr/src/ep2017/conference/ical.py", line 101, in encode
    yield content(name, value, params)
  File "/usr/src/ep2017/conference/ical.py", line 42, in content
    return encode('%s:%s' % (name, value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)
```

**Comment by umgelurgel** [comment]
Right now we no longer support the ical views, the app is used instead to manage the calendar, resolving.
